require(GeneFamilies)
options(mc.cores = detectCores())

message("USAGE: Rscript path/2/GeneFamilies/exec/loadGeneFamilies.R path/2/GeneFamilies/data mcl_output.txt")
message("EXPECTED INPUT FORMATS:")
message(" - mcl_output.txt is the textual output generated by the markob clustering tool mcl used on the all vs all sequence similarity search results. A single cluster (family) is expected per line and gene members to be separated by TAB.")

input.args <- commandArgs(trailingOnly = TRUE)

families.genes.df <- readMclOutput(input.args[[2]])
families.lst <- mclDataFrameAsList(families.genes.df)
family.nms <- names(families.lst)
families.df <- Reduce(rbind, mclapply(family.nms, function(fam.nm) {
    fam.genes <- families.lst[[fam.nm]]
    fam.specs <- setNames(lapply(fam.genes, speciesForGeneId), fam.genes)
    data.frame(id = fam.nm, ath = length(which(fam.specs == "ath")), cla = length(which(fam.specs == 
        "cla")), cme = length(which(fam.specs == "cme")), csa = length(which(fam.specs == 
        "csa")), fve = length(which(fam.specs == "fve")), size = length(fam.genes), 
        stringsAsFactors = FALSE)
}))

#' Save parsed data:
save(families.genes.df, families.lst, families.df, file = file.path(input.args[[1]], 
    "families.RData"))
