require(GeneFamilies)
options(mc.cores = detectCores())

message("USAGE: Rscript path/2/GeneFamilies/exec/loadGeneFamilies.R path/2/GeneFamilies/data mcl_output.txt")
message("EXPECTED INPUT FORMATS:")
message(" - mcl_output.txt is the textual output generated by the markob clustering tool mcl used on the all vs all sequence similarity search results. A single cluster (family) is expected per line and gene members to be separated by TAB.")

input.args <- commandArgs(trailingOnly = TRUE)

families.genes.df <- readMclOutput(input.args[[2]])
families.lst <- mclDataFrameAsList(families.genes.df)
families.df <- data.frame( Family=c(), ath=c(), cla=c(), cme=c(), csa=c(), fve=c(), size=c(), stringsAsFactors=FALSE )
family.nms <- names(families.lst)
for ( fam.nm in family.nms ) {
  fam.genes <- families.lst[[fam.nm]]
  fam.specs <- setNames( lapply( fam.genes, speciesForGeneId ), fam.genes )
  i <- nrow(families.df) + 1
  families.df[i, "id"] <- fam.nm
  families.df[i, "ath"] <- length( which( fam.specs == "ath" ) )
  families.df[i, "cla"] <- length( which( fam.specs == "cla" ) )
  families.df[i, "cme"] <- length( which( fam.specs == "cme" ) )
  families.df[i, "csa"] <- length( which( fam.specs == "csa" ) )
  families.df[i, "fve"] <- length( which( fam.specs == "fve" ) )
  families.df[i, "size"] <- length(fam.genes)
}

#' Save parsed data:
save(families.genes.df, families.lst, families.df, file = file.path(input.args[[1]], 
    "families.RData"))
